package com.discipolat.common.enums;
public enum TypeNotification {
    RAPPORT_NON_SOUMIS, ABSENCE_48H, RAPPORT_FAMILLE_NON_SOUMIS, ALERTE_ABSENCE, INFORMATION, PRIERE_EXAUCEE,
    // Transferts (workflow configurable)
    TRANSFERT_DEMANDE, TRANSFERT_VALIDATION, TRANSFERT_VALIDEE, TRANSFERT_REFUSEE,
    TRANSFERT_INFOS_DEMANDEES, TRANSFERT_CORRECTION, TRANSFERT_EXECUTEE, TRANSFERT_ANNULEE,
    TRANSFERT_DELAI_DEPASSE
}
