import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:discipolat_mobile/data/services/api_service.dart';
import 'package:discipolat_mobile/presentation/screens/event_checklist/event_checklist_screen.dart';

class _FakeApiService extends ApiService {
  _FakeApiService({this.fail = false}) : super(baseUrl: 'http://fake');
  final bool fail;
  final List<String> getPaths = [];
  final List<String> postedPaths = [];
  int toggles = 0;

  @override
  Future<Response> get(String path, {Map<String, dynamic>? params}) async {
    getPaths.add(path);
    if (fail) throw DioException(requestOptions: RequestOptions(path: path));
    if (path == '/event-checklists') {
      return Response(
        requestOptions: RequestOptions(path: path),
        statusCode: 200,
        data: [
          {'id': 'task-1', 'title': 'Réserver la salle', 'status': 'COMPLETED', 'isAutoGenerated': true},
          {'id': 'task-2', 'title': 'Préparer le son', 'status': 'PENDING', 'isAutoGenerated': false},
        ],
      );
    }
    return Response(requestOptions: RequestOptions(path: path), statusCode: 200, data: []);
  }

  @override
  Future<Response> post(String path, {dynamic data}) async {
    postedPaths.add(path);
    toggles++;
    return Response(requestOptions: RequestOptions(path: path), statusCode: 200, data: {'ok': true});
  }
}

void main() {
  group('EventChecklistScreen', () {
    testWidgets('renders app bar', (tester) async {
      await tester.pumpWidget(MaterialApp(home: EventChecklistScreen(apiService: _FakeApiService())));
      await tester.pumpAndSettle();
      expect(find.text('✅ Checklists'), findsOneWidget);
    });

    testWidgets('shows tasks and progress counter from API', (tester) async {
      final api = _FakeApiService();
      await tester.pumpWidget(MaterialApp(home: EventChecklistScreen(apiService: api)));
      await tester.pumpAndSettle();
      expect(find.text('1 / 2 tâches terminées'), findsOneWidget);
      expect(find.text('Réserver la salle'), findsOneWidget);
      expect(find.text('Préparer le son'), findsOneWidget);
      expect(find.text('Auto-générée'), findsOneWidget);
    });

    testWidgets('toggling a task calls the real endpoint then reloads', (tester) async {
      final api = _FakeApiService();
      await tester.pumpWidget(MaterialApp(home: EventChecklistScreen(apiService: api)));
      await tester.pumpAndSettle();

      await tester.tap(find.text('Préparer le son'));
      await tester.pumpAndSettle();

      expect(api.postedPaths, contains('/event-checklists/task-2/toggle'));
      // Rechargement après toggle : au moins 2 GET.
      expect(api.getPaths.where((p) => p == '/event-checklists').length, greaterThanOrEqualTo(2));
    });

    testWidgets('shows error state with retry', (tester) async {
      await tester.pumpWidget(MaterialApp(home: EventChecklistScreen(apiService: _FakeApiService(fail: true))));
      await tester.pumpAndSettle();
      expect(find.text('Impossible de charger les checklists.'), findsOneWidget);
      expect(find.text('Réessayer'), findsOneWidget);
    });
  });
}
