package com.discipolat.modules.eventChecklist.domain;

import com.discipolat.common.multitenancy.TenantContext;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.*;

@Service
@Transactional
public class EventChecklistService {

    private final EventChecklistItemRepository checklistRepo;

    // Templates for auto-generated checklists by event type
    private static final Map<String, List<String>> CHECKLIST_TEMPLATES = Map.of(
        "Culte", List.of("Son & lumière vérifiés", "Projections prêtes", "Accueil préparé", "Priere d'ouverture préparée", "Tithe/Offrande collecteurs prêts", "Relève enfants préparée", "Hymnes planifiés"),
        "Baptême", List.of("Bassin préparé", "Serviettes disponibles", "Certificats imprimés", "Photographe convoqué", "Témoins identifiés", "Hymnes de baptême choisis"),
        "Mariage", List.of("Salle décorée", "Dossier administratif vérifié", "Pasteur confirmé", "Musiciens réservés", "Traiteur planifié", "Photographe convoqué"),
        "Conférence", List.of("Salle réservée", "Invités confirmés", "Matériel projection", "Traducteurs disponibles", "Hébergement confirmé", "Transport planifié"),
        "Événement Jeunesse", List.of("Animation préparée", "Games & activités", "Snacks/boissons", "Sécurité renforcée", "Premiers soins disponible"),
        "DEFAULT", List.of("Salle réservée", "Équipe d'accueil prête", "Matériel technique vérifié", "Communication envoyée", "Comptes/Offrande prêts")
    );

    public EventChecklistService(EventChecklistItemRepository checklistRepo) {
        this.checklistRepo = checklistRepo;
    }

    public List<EventChecklistItem> getByEvent(UUID eventId) {
        return checklistRepo.findByTenantIdAndEventIdOrderByOrderIndexAsc(TenantContext.getCurrentTenantId(), eventId);
    }

    public List<EventChecklistItem> generateForEvent(UUID eventId, String eventType, LocalDateTime eventDate) {
        List<String> template = CHECKLIST_TEMPLATES.getOrDefault(eventType, CHECKLIST_TEMPLATES.get("DEFAULT"));
        List<EventChecklistItem> items = new ArrayList<>();
        int index = 0;
        for (String title : template) {
            EventChecklistItem item = new EventChecklistItem();
            item.setTenantId(TenantContext.getCurrentTenantId());
            item.setEventId(eventId);
            item.setTitle(title);
            item.setOrderIndex(index++);
            item.setIsAutoGenerated(true);
            items.add(checklistRepo.save(item));
        }
        return items;
    }

    public EventChecklistItem addItem(EventChecklistItem item) {
        item.setTenantId(TenantContext.getCurrentTenantId());
        return checklistRepo.save(item);
    }

    public EventChecklistItem toggleItem(UUID id) {
        EventChecklistItem item = checklistRepo.findById(id).orElseThrow();
        if (item.getStatus() == EventChecklistItem.Status.COMPLETED) {
            item.setStatus(EventChecklistItem.Status.PENDING);
            item.setCompletedAt(null);
        } else {
            item.setStatus(EventChecklistItem.Status.COMPLETED);
            item.setCompletedAt(LocalDateTime.now());
        }
        return checklistRepo.save(item);
    }

    public void deleteItem(UUID id) {
        checklistRepo.deleteById(id);
    }

    public Map<String, Object> getEventProgress(UUID eventId) {
        UUID tenantId = TenantContext.getCurrentTenantId();
        long total = checklistRepo.findByTenantIdAndEventIdOrderByOrderIndexAsc(tenantId, eventId).size();
        long completed = checklistRepo.countByTenantIdAndEventIdAndStatus(tenantId, eventId, EventChecklistItem.Status.COMPLETED);
        Map<String, Object> result = new HashMap<>();
        result.put("total", total);
        result.put("completed", completed);
        result.put("percentage", total > 0 ? Math.round(completed * 100.0 / total) : 0);
        return result;
    }
}
