import 'package:flutter/material.dart';
import '../../../data/services/api_service.dart';

/// Checklists événementielles — branché sur GET /api/v1/event-checklists.
class EventChecklistScreen extends StatefulWidget {
  const EventChecklistScreen({super.key, this.apiService});
  final ApiService? apiService;

  @override
  State<EventChecklistScreen> createState() => _EventChecklistScreenState();
}

class _EventChecklistScreenState extends State<EventChecklistScreen> {
  late final ApiService _api = widget.apiService ?? ApiService();
  List<dynamic> _items = [];
  bool _loading = true;
  String? _error;

  @override
  void initState() { super.initState(); _load(); }

  Future<void> _load() async {
    setState(() { _loading = true; _error = null; });
    try {
      final res = await _api.get('/event-checklists');
      final d = res.data;
      setState(() { _items = d is List ? d : <dynamic>[]; _loading = false; });
    } catch (_) {
      setState(() { _error = 'Impossible de charger les checklists.'; _loading = false; });
    }
  }

  Future<void> _toggle(String id) async {
    try {
      await _api.post('/event-checklists/' + id + '/toggle');
      await _load();
    } catch (_) {}
  }

  @override
  Widget build(BuildContext context) {
    final completed = _items.where((x) => x is Map && x['status'] == 'COMPLETED').length;
    return Scaffold(
      appBar: AppBar(title: const Text('✅ Checklists'), backgroundColor: Colors.green.shade700, foregroundColor: Colors.white),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : _error != null
              ? Center(child: Column(mainAxisSize: MainAxisSize.min, children: [
                  Padding(padding: const EdgeInsets.all(24), child: Text(_error!, textAlign: TextAlign.center)),
                  ElevatedButton(onPressed: _load, child: const Text('Réessayer')),
                ]))
              : RefreshIndicator(
                  onRefresh: _load,
                  child: Column(children: [
                    Padding(
                      padding: const EdgeInsets.all(12),
                      child: Text(completed.toString() + ' / ' + _items.length.toString() + ' tâches terminées', style: const TextStyle(fontSize: 12)),
                    ),
                    Expanded(
                      child: _items.isEmpty
                          ? const Center(child: Text('Aucune tâche de checklist.'))
                          : ListView.builder(
                              padding: const EdgeInsets.symmetric(horizontal: 16),
                              itemCount: _items.length,
                              itemBuilder: (context, i) {
                                final it = _items[i] as Map<String, dynamic>;
                                final status = it['status']?.toString() ?? 'PENDING';
                                return CheckboxListTile(
                                  value: status == 'COMPLETED',
                                  onChanged: (_) => _toggle(it['id'].toString()),
                                  title: Text(it['title']?.toString() ?? 'Tâche', style: TextStyle(fontSize: 13, decoration: status == 'COMPLETED' ? TextDecoration.lineThrough : null)),
                                  subtitle: it['isAutoGenerated'] == true ? const Text('Auto-générée', style: TextStyle(fontSize: 10)) : null,
                                );
                              },
                            ),
                    ),
                  ]),
                ),
    );
  }
}
