package com.discipolat.modules.familyMeeting.domain;

import com.discipolat.common.multitenancy.TenantContext;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;

@Service
@Transactional
public class FamilyMeetingService {

    private final FamilyMeetingRepository meetingRepo;

    public FamilyMeetingService(FamilyMeetingRepository meetingRepo) { this.meetingRepo = meetingRepo; }

    /** Auto-generate an agenda based on family alerts */
    public FamilyMeeting generateAgenda(UUID familyId) {
        FamilyMeeting meeting = new FamilyMeeting();
        meeting.setTenantId(TenantContext.getCurrentTenantId());
        meeting.setFamilyId(familyId);
        meeting.setStatus(FamilyMeeting.Status.DRAFT);
        meeting.setIsAutoGenerated(true);
        meeting.setCreatedAt(LocalDateTime.now());

        StringBuilder agenda = new StringBuilder();
        agenda.append("ORDRE DU JOUR — Réunion de famille\n\n");
        agenda.append("1. Prière d'ouverture\n");
        agenda.append("2. Lecture de la Parole du jour\n");
        agenda.append("3. Point sur les membres absents (3 dernières semaines)\n");
        agenda.append("4. Rapports en attente de validation\n");
        agenda.append("5. Alertes et accompagnements nécessaires\n");
        agenda.append("6. Événements à venir et planification\n");
        agenda.append("7. Partage de témoignages\n");
        agenda.append("8. Prière de clôture\n");
        meeting.setAgenda(agenda.toString());
        return meetingRepo.save(meeting);
    }

    public FamilyMeeting create(FamilyMeeting meeting) {
        meeting.setTenantId(TenantContext.getCurrentTenantId());
        return meetingRepo.save(meeting);
    }

    public FamilyMeeting complete(UUID id, String minutes) {
        FamilyMeeting meeting = meetingRepo.findById(id).orElseThrow();
        meeting.setStatus(FamilyMeeting.Status.COMPLETED);
        meeting.setMinutes(minutes);
        return meetingRepo.save(meeting);
    }

    public List<FamilyMeeting> listByFamily(UUID familyId) {
        return meetingRepo.findByTenantIdAndFamilyIdOrderByScheduledAtDesc(TenantContext.getCurrentTenantId(), familyId);
    }

    public List<FamilyMeeting> listAll() {
        return meetingRepo.findByTenantIdOrderByScheduledAtDesc(TenantContext.getCurrentTenantId());
    }
}
