import { useState } from 'react';
import { useI18n } from '@/i18n';
import { ClipboardCheck, Check, Circle, Plus, Sparkles } from 'lucide-react';

interface CheckItem { id: string; title: string; status: string; assignedTo?: string; isAutoGenerated: boolean; }
interface EventChecklist { eventId: string; eventName: string; items: CheckItem[]; progress: number; }

export default function EventChecklistsPage() {
  const { t } = useI18n();
  const MOCK: EventChecklist[] = [
    { eventId: '1', eventName: 'Culte du dimanche 24 Août', progress: 71, items: [
      { id: '1', title: 'Son & lumière vérifiés', status: 'COMPLETED', isAutoGenerated: true },
      { id: '2', title: 'Projections prêtes', status: 'COMPLETED', isAutoGenerated: true },
      { id: '3', title: 'Accueil préparé', status: 'IN_PROGRESS', assignedTo: 'Marie', isAutoGenerated: true },
      { id: '4', title: 'Comptes/Offrande prêts', status: 'PENDING', isAutoGenerated: true },
      { id: '5', title: 'Relève enfants préparée', status: 'PENDING', isAutoGenerated: true },
      { id: '6', title: 'Hymnes planifiés', status: 'COMPLETED', isAutoGenerated: true },
      { id: '7', title: 'Priere d\'ouverture préparée', status: 'COMPLETED', isAutoGenerated: true },
    ]},
    { eventId: '2', eventName: 'Retraite Jeunesse 30 Août', progress: 25, items: [
      { id: '8', title: 'Salle réservée', status: 'COMPLETED', isAutoGenerated: true },
      { id: '9', title: 'Animation préparée', status: 'PENDING', isAutoGenerated: true },
      { id: '10', title: 'Snacks/boissons', status: 'PENDING', isAutoGenerated: true },
      { id: '11', title: 'Sécurité renforcée', status: 'PENDING', isAutoGenerated: true },
    ]},
  ];

  return (
    <div className="space-y-6 p-6">
      <h1 className="text-2xl font-bold text-white flex items-center gap-2"><ClipboardCheck className="text-emerald-400" /> {t('checklist.title') || 'Checklists événementielles'}</h1>
      <div className="space-y-4">
        {MOCK.map(event => (
          <div key={event.eventId} className="bg-white/5 backdrop-blur rounded-2xl p-5 border border-white/10">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-white">{event.eventName}</h2>
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-400">{event.progress}%</span>
                <div className="w-24 h-2 bg-gray-700 rounded-full overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-emerald-500 to-green-400 rounded-full" style={{ width: `${event.progress}%` }} />
                </div>
              </div>
            </div>
            <div className="space-y-2">
              {event.items.map(item => (
                <div key={item.id} className="flex items-center gap-3 p-2 rounded-lg hover:bg-white/5 transition">
                  {item.status === 'COMPLETED' ? <Check className="w-5 h-5 text-green-400" /> : <Circle className="w-5 h-5 text-gray-500" />}
                  <span className={`text-sm flex-1 ${item.status === 'COMPLETED' ? 'text-gray-400 line-through' : 'text-white'}`}>{item.title}</span>
                  {item.isAutoGenerated && <span className="text-xs text-purple-400 flex items-center gap-1"><Sparkles className="w-3 h-3" />Auto</span>}
                  {item.assignedTo && <span className="text-xs text-blue-400">{item.assignedTo}</span>}
                </div>
              ))}
            </div>
            <button className="mt-3 flex items-center gap-2 text-sm text-gray-400 hover:text-white transition"><Plus className="w-4 h-4" /> Ajouter un élément</button>
          </div>
        ))}
      </div>
    </div>
  );
}
