import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useI18n } from '@/i18n';
import api, { getErrorMessage } from '@/lib/api';
import SkeletonLoader from '@/components/shared/SkeletonLoader';
import EmptyState from '@/components/shared/EmptyState';
import toast from 'react-hot-toast';
import { ClipboardCheck, Check, Circle, Plus, Sparkles } from 'lucide-react';

interface CheckItem { id: string; title: string; status: string; assignedTo?: string; isAutoGenerated: boolean; }
interface EventChecklist { eventId: string; eventName: string; items: CheckItem[]; progress: number; }

export default function EventChecklistsPage() {
  const { t } = useI18n();
  const queryClient = useQueryClient();

  const { data: checklists = [], isLoading, error } = useQuery({
    queryKey: ['event-checklists'],
    queryFn: async () => {
      const res = await api.get('/event-checklists');
      // EventChecklistItem { id, eventId, title, status, assignedTo, orderIndex, isAutoGenerated }
      const items: Array<Record<string, unknown>> = res.data as Array<Record<string, unknown>>;
      const byEvent = new Map<string, CheckItem[]>();
      items.forEach((i) => {
        const eid = String(i.eventId);
        if (!byEvent.has(eid)) byEvent.set(eid, []);
        byEvent.get(eid)!.push({
          id: String(i.id),
          title: String(i.title ?? ''),
          status: String(i.status ?? 'PENDING'),
          assignedTo: i.assignedTo as string | undefined,
          isAutoGenerated: Boolean(i.isAutoGenerated),
        });
      });
      return Array.from(byEvent.entries()).map(([eventId, items]) => {
        const total = items.length;
        const completed = items.filter((i) => i.status === 'COMPLETED').length;
        return {
          eventId,
          eventName: `Événement #${eventId.slice(0, 8)}`,
          items,
          progress: total > 0 ? Math.round((completed / total) * 100) : 0,
        };
      }) as EventChecklist[];
    },
    retry: false,
  });

  const toggleMutation = useMutation({
    mutationFn: async (id: string) => { await api.post(`/event-checklists/${id}/toggle`); },
    onSuccess: () => { toast.success('Statut mis à jour'); queryClient.invalidateQueries({ queryKey: ['event-checklists'] }); },
    onError: () => toast.error('Erreur'),
  });

  if (isLoading) return <SkeletonLoader lines={3} variant="card" />;
  if (error) return <div className="text-red-500 p-6">{getErrorMessage(error)}</div>;
  if (checklists.length === 0) return <EmptyState title="Aucune checklist" message="Aucune checklist événementielle." />;

  return (
    <div className="space-y-6 p-6">
      <h1 className="text-2xl font-bold text-white flex items-center gap-2"><ClipboardCheck className="text-emerald-400" /> {t('checklist.title') || 'Checklists événementielles'}</h1>
      <div className="space-y-4">
        {checklists.map(event => (
          <div key={event.eventId} className="bg-white/5 backdrop-blur rounded-2xl p-5 border border-white/10">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-white">{event.eventName}</h2>
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-400">{event.progress}%</span>
                <div className="w-24 h-2 bg-gray-700 rounded-full overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-emerald-500 to-green-400 rounded-full" style={{ width: `${event.progress}%` }} />
                </div>
              </div>
            </div>
            <div className="space-y-2">
              {event.items.map(item => (
                                <div key={item.id} className="flex items-center gap-3 p-2 rounded-lg hover:bg-white/5 transition" onClick={() => toggleMutation.mutate(item.id)}>
                  {item.status === 'COMPLETED' ? <Check className="w-5 h-5 text-green-400" /> : <Circle className="w-5 h-5 text-gray-500" />}
                  <span className={`text-sm flex-1 ${item.status === 'COMPLETED' ? 'text-gray-400 line-through' : 'text-white'}`}>{item.title}</span>
                  {item.isAutoGenerated && <span className="text-xs text-purple-400 flex items-center gap-1"><Sparkles className="w-3 h-3" />Auto</span>}
                  {item.assignedTo && <span className="text-xs text-blue-400">{item.assignedTo}</span>}
                </div>
              ))}
            </div>
            <button className="mt-3 flex items-center gap-2 text-sm text-gray-400 hover:text-white transition"><Plus className="w-4 h-4" /> Ajouter un élément</button>
          </div>
        ))}
      </div>
    </div>
  );
}
