import { useState } from 'react';
import { useI18n } from '@/i18n';
import { Users, Sparkles, CheckCircle, Calendar, Plus, FileText } from 'lucide-react';

interface FamilyMeeting { id: string; familyName: string; agenda: string; status: string; scheduledAt?: string; attendeesCount: number; isAutoGenerated: boolean; }

export default function FamilyMeetingPage() {
  const { t } = useI18n();
  const MOCK: FamilyMeeting[] = [
    { id: '1', familyName: 'Famille Mbarga', agenda: '1. Prière d\'ouverture\n2. Point absents\n3. Rapports en attente\n4. Événements à venir\n5. Prière de clôture', status: 'COMPLETED', attendeesCount: 5, isAutoGenerated: true },
    { id: '2', familyName: 'Famille Ngo', agenda: '1. Prière d\'ouverture\n2. Point absents\n3. Alertes accompagnement\n4. Partage témoignages\n5. Prière de clôture', status: 'SCHEDULED', scheduledAt: '2026-08-25', attendeesCount: 0, isAutoGenerated: true },
  ];
  const statusColor = (s: string) => s === 'COMPLETED' ? 'bg-green-500/20 text-green-400' : s === 'SCHEDULED' ? 'bg-blue-500/20 text-blue-400' : 'bg-gray-500/20 text-gray-400';

  return (
    <div className="space-y-6 p-6">
      <h1 className="text-2xl font-bold text-white flex items-center gap-2"><Users className="text-emerald-400" /> {t('familyMeeting.title') || 'Réunions de famille automatisées'}</h1>
      <div className="space-y-4">
        {MOCK.map(m => (
          <div key={m.id} className="bg-white/5 backdrop-blur rounded-2xl p-5 border border-white/10">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-3">
                <h3 className="text-white font-semibold">{m.familyName}</h3>
                <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusColor(m.status)}`}>{m.status}</span>
                {m.isAutoGenerated && <span className="text-purple-400 text-xs flex items-center gap-1"><Sparkles className="w-3 h-3" />Auto</span>}
              </div>
              {m.scheduledAt && <span className="text-xs text-gray-400">{m.scheduledAt}</span>}
            </div>
            <div className="bg-white/5 rounded-xl p-3 mb-3">
              <h4 className="text-xs font-medium text-gray-400 mb-2">ORDRE DU JOUR</h4>
              <div className="text-sm text-gray-300 whitespace-pre-line">{m.agenda}</div>
            </div>
            <div className="flex items-center gap-2 text-xs text-gray-400">
              <span>{m.attendeesCount} participants</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
