import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useI18n } from '@/i18n';
import api, { getErrorMessage } from '@/lib/api';
import SkeletonLoader from '@/components/shared/SkeletonLoader';
import EmptyState from '@/components/shared/EmptyState';
import toast from 'react-hot-toast';
import { Users, Sparkles, CheckCircle, Calendar, Plus, FileText } from 'lucide-react';

interface FamilyMeeting { id: string; familyName: string; agenda: string; status: string; scheduledAt?: string; attendeesCount: number; isAutoGenerated: boolean; }

export default function FamilyMeetingPage() {
  const { t } = useI18n();
  const queryClient = useQueryClient();
  const [completingId, setCompletingId] = useState<string | null>(null);
  const [minutes, setMinutes] = useState('');

  const { data: meetings = [], isLoading, error } = useQuery({
    queryKey: ['family-meetings'],
    queryFn: async () => {
      const res = await api.get('/family-meetings');
      // FamilyMeeting { id, familyId, agenda, status, scheduledAt, attendeesCount, isAutoGenerated }
      return (res.data as Array<Record<string, unknown>>).map((m) => ({
        id: String(m.id),
        familyName: m.familyName ? String(m.familyName) : (m.familyId ? `Famille #${String(m.familyId).slice(0, 8)}` : 'Famille'),
        agenda: String(m.agenda ?? ''),
        status: String(m.status ?? 'DRAFT'),
        scheduledAt: m.scheduledAt as string | undefined,
        attendeesCount: Number(m.attendeesCount ?? 0),
        isAutoGenerated: Boolean(m.isAutoGenerated),
      })) as FamilyMeeting[];
    },
    retry: false,
  });

  const completeMutation = useMutation({
    mutationFn: async ({ id, minutes }: { id: string; minutes: string }) => { await api.post(`/family-meetings/${id}/complete`, { minutes }); },
    onSuccess: () => { toast.success('Réunion clôturée'); queryClient.invalidateQueries({ queryKey: ['family-meetings'] }); },
    onError: () => toast.error('Erreur'),
  });

  const statusColor = (s: string) => s === 'COMPLETED' ? 'bg-green-500/20 text-green-400' : s === 'SCHEDULED' ? 'bg-blue-500/20 text-blue-400' : 'bg-gray-500/20 text-gray-400';

  if (isLoading) return <SkeletonLoader lines={3} variant="card" />;
  if (error) return <div className="text-red-500 p-6">{getErrorMessage(error)}</div>;
  if (meetings.length === 0) return <EmptyState title="Aucune réunion" message="Aucune réunion de famille programmée." />;

  return (
    <div className="space-y-6 p-6">
      <h1 className="text-2xl font-bold text-white flex items-center gap-2"><Users className="text-emerald-400" /> {t('familyMeeting.title') || 'Réunions de famille automatisées'}</h1>
      <div className="space-y-4">
                {meetings.map(m => (
          <div key={m.id} className="bg-white/5 backdrop-blur rounded-2xl p-5 border border-white/10">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-3">
                <h3 className="text-white font-semibold">{m.familyName}</h3>
                <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${statusColor(m.status)}`}>{m.status}</span>
                {m.isAutoGenerated && <span className="text-purple-400 text-xs flex items-center gap-1"><Sparkles className="w-3 h-3" />Auto</span>}
              </div>
              {m.scheduledAt && <span className="text-xs text-gray-400">{m.scheduledAt}</span>}
            </div>
            <div className="bg-white/5 rounded-xl p-3 mb-3">
              <h4 className="text-xs font-medium text-gray-400 mb-2">ORDRE DU JOUR</h4>
              <div className="text-sm text-gray-300 whitespace-pre-line">{m.agenda}</div>
            </div>
            <div className="flex items-center gap-2 text-xs text-gray-400">
              <span>{m.attendeesCount} participants</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
