import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api, { getErrorMessage } from '@/lib/api';
import { MapPin, Loader2, Plus, Calendar, RefreshCw } from 'lucide-react';
import toast from 'react-hot-toast';

interface PastoralVisit {
  id: string;
  soulId: string;
  soulName?: string;
  pastorName?: string;
  scheduledDate: string;
  status: string;
  notes?: string;
  isAutoGenerated: boolean;
}

const STATUS_STYLE: Record<string, string> = {
  SCHEDULED: 'text-blue-400 bg-blue-500/20',
  COMPLETED: 'text-green-400 bg-green-500/20',
  CANCELLED: 'text-red-400 bg-red-500/20',
  RESCHEDULED: 'text-yellow-400 bg-yellow-500/20',
};

export default function PastoralVisitsPage() {
  const qc = useQueryClient();
  const [rescheduleId, setRescheduleId] = useState<string | null>(null);
  const [newDate, setNewDate] = useState('');

  const { data: visits = [], isLoading } = useQuery({
    queryKey: ['pastoral-visits'],
    queryFn: async () => (await api.get('/pastoral-visits')).data as PastoralVisit[],
  });

  const autoGenerateMutation = useMutation({
    mutationFn: async () => api.post('/pastoral-visits/auto-generate'),
    onSuccess: () => { toast.success('Visites auto-générées'); qc.invalidateQueries({ queryKey: ['pastoral-visits'] }); },
    onError: (e) => toast.error(getErrorMessage(e)),
  });

  const rescheduleMutation = useMutation({
    mutationFn: async ({ id, date }: { id: string; date: string }) =>
      api.post(`/pastoral-visits/${id}/reschedule`, { newDate: date }),
    onSuccess: () => { toast.success('Visite reprogrammée'); setRescheduleId(null); setNewDate(''); qc.invalidateQueries({ queryKey: ['pastoral-visits'] }); },
    onError: (e) => toast.error(getErrorMessage(e)),
  });

  const scheduled = visits.filter((v) => v.status === 'SCHEDULED');
  const completed = visits.filter((v) => v.status === 'COMPLETED');

  return (
    <div className="page-container">
      <div className="page-header">
        <div className="p-3 rounded-xl bg-gradient-to-br from-blue-500 to-indigo-600 text-white shadow-lg">
          <MapPin className="w-6 h-6" />
        </div>
        <div>
          <h1 className="page-title">Visites pastorales</h1>
          <p className="page-subtitle">Planification et suivi des visites</p>
        </div>
        <button onClick={() => autoGenerateMutation.mutate()} disabled={autoGenerateMutation.isPending}
          className="btn-primary btn-sm ml-auto inline-flex items-center gap-1">
          {autoGenerateMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />} Auto-générer
        </button>
      </div>

      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { label: 'Total', value: visits.length, color: 'text-blue-600' },
          { label: 'Planifiées', value: scheduled.length, color: 'text-amber-600' },
          { label: 'Complétées', value: completed.length, color: 'text-green-600' },
        ].map((s) => (
          <div key={s.label} className="stat-card">
            <p className={`stat-value ${s.color}`}>{s.value}</p>
            <p className="stat-label">{s.label}</p>
          </div>
        ))}
      </div>

      {isLoading ? (
        <div className="flex justify-center py-12"><Loader2 className="w-8 h-8 animate-spin text-primary-500" /></div>
      ) : visits.length === 0 ? (
        <div className="glass-card p-10 text-center text-gray-500">Aucune visite pastorale</div>
      ) : (
        <div className="space-y-3">
          {visits.map((v) => (
            <div key={v.id} className="glass-card p-5">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_STYLE[v.status] ?? 'text-gray-400 bg-gray-500/20'}`}>{v.status}</span>
                    {v.isAutoGenerated && <span className="text-[10px] text-purple-400 bg-purple-500/20 px-2 py-0.5 rounded-full">Auto-générée</span>}
                  </div>
                  <p className="text-sm font-medium text-gray-800 dark:text-gray-200">{v.soulName ?? `Membre #${v.soulId.slice(0, 8)}`}</p>
                  {v.pastorName && <p className="text-xs text-gray-400">Pasteur: {v.pastorName}</p>}
                  <div className="flex items-center gap-2 mt-1 text-[11px] text-gray-500">
                    <Calendar className="w-3 h-3" />
                    {new Date(v.scheduledDate).toLocaleDateString('fr-FR')}
                  </div>
                  {v.notes && <p className="text-xs text-gray-500 mt-1">{v.notes}</p>}
                </div>
                {v.status === 'SCHEDULED' && (
                  <div className="ml-4">
                    {rescheduleId === v.id ? (
                      <div className="flex items-center gap-2">
                        <input type="datetime-local" value={newDate} onChange={(e) => setNewDate(e.target.value)}
                          className="input text-xs py-1 px-2" />
                        <button onClick={() => rescheduleMutation.mutate({ id: v.id, date: newDate })} disabled={!newDate}
                          className="btn-sm px-2 py-1 rounded bg-green-600 text-white text-xs hover:bg-green-700">
                          {rescheduleMutation.isPending ? <Loader2 className="w-3 h-3 animate-spin" /> : 'OK'}
                        </button>
                        <button onClick={() => setRescheduleId(null)} className="text-xs text-gray-400 hover:text-white">Annuler</button>
                      </div>
                    ) : (
                      <button onClick={() => setRescheduleId(v.id)}
                        className="btn-sm px-3 py-1.5 rounded-lg bg-white/5 text-gray-400 text-xs hover:bg-white/10 flex items-center gap-1">
                        <Calendar className="w-3 h-3" /> Reprogrammer
                      </button>
                    )}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
