package com.discipolat.modules.discipline.domain;

public enum CategorieDiscipline {
    COMPORTEMENT,
    CONDUITE,
    HABILLEMENT,
    VIE_SPIRITUELLE,
    PONCTUALITE,
    PARTICIPATION,
    FIDELITE,
    ENGAGEMENT,
    REPROCHE,
    SANCTION,
    LITIGE,
    CONFLIT,
    SCANDALE,
    RELATION_PROBLEMATIQUE,
    FLIRT_INAPPROPRIE,
    DEGAT_MATERIEL,
    DEGAT_RELATIONNEL,
    RESOLUTION,
    TEMOIGNAGE_MEMBRE,
    TEMOIGNAGE_RESPONSABLE,
    TEMOIGNAGE_CHEF,
    COMMENTAIRE_PASTORAL,
    AUTRE
}
